from __future__ import annotations

import os
import shutil
from pathlib import Path

from xzssh.cli.helpers import load_config_or_error
from xzssh.cli.ui import (
    print_error,
    print_errors,
    print_info,
    print_success,
    print_warnings,
    status,
)
from xzssh.generator import HEADER_LINE, render_openssh
from xzssh.platform import ensure_secure_file_permissions
from xzssh.validator import validate_config


def run(
    config_path: Path,
    output_path: Path,
    suggest_ports: bool,
    force: bool = False,
) -> int:
    with status("Reading source configuration"):
        config = load_config_or_error(config_path)
    if config is None:
        return 1

    with status("Final validation before generation"):
        result = validate_config(
            config, suggest_ports=suggest_ports, source_path=config_path
        )
    if result.errors:
        print_errors(result.errors)
        return 1
    if result.warnings:
        print_warnings(result.warnings)

    if not _safe_to_overwrite(output_path, force):
        print_error(
            f"Refusing to overwrite {output_path}: file exists and was not "
            "generated by xzSSH.\n"
            "Re-run with --force to overwrite anyway "
            "(a .bak copy will be saved)."
        )
        return 1

    backup_path = _backup_existing(output_path)
    if backup_path is not None:
        print_info(f"Saved backup of existing file at {backup_path}")

    with status(f"Generating OpenSSH config at {output_path}"):
        content = render_openssh(config, config_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = output_path.with_name(output_path.name + ".tmp")
        try:
            tmp_path.write_text(content, encoding="utf-8")
            warning = ensure_secure_file_permissions(tmp_path)
            os.replace(tmp_path, output_path)
        except OSError:
            if tmp_path.exists():
                try:
                    tmp_path.unlink()
                except OSError:
                    pass
            raise

    if warning:
        print_warnings([warning])
    print_success(f"OpenSSH configuration has been generated at {output_path}")
    return 0


def _safe_to_overwrite(output_path: Path, force: bool) -> bool:
    """Allow overwrite if the file is absent, empty, xzSSH-generated, or --force."""
    if force or not output_path.exists():
        return True
    try:
        if output_path.stat().st_size == 0:
            return True
        with output_path.open("r", encoding="utf-8", errors="replace") as f:
            first_line = f.readline().rstrip("\n").rstrip("\r")
    except OSError:
        return False
    return first_line == HEADER_LINE


def _backup_existing(output_path: Path) -> Path | None:
    if not output_path.exists() or output_path.stat().st_size == 0:
        return None
    backup_path = output_path.with_name(output_path.name + ".bak")
    shutil.copy2(output_path, backup_path)
    return backup_path
