from pathlib import Path

from xzssh.generator import render_openssh, resolve_identity_file
from xzssh.model import Config, Host, LocalForward


def test_render_openssh_output(tmp_path: Path) -> None:
    config = Config(
        version=1,
        hosts=[
            Host(
                alias="db",
                host_name="db.example.com",
                user="alice",
                port=22,
                identity_file="~/.ssh/id_ed25519",
                local_forwards=[LocalForward(5432, "127.0.0.1", 5432)],
            )
        ],
    )

    config_path = tmp_path / "xzssh.json"
    output = render_openssh(config, config_path)

    resolved_identity = resolve_identity_file("~/.ssh/id_ed25519", config_path)
    expected = (
        "# Generated by xzSSH - DO NOT EDIT\n"
        "Host db\n"
        "  HostName db.example.com\n"
        "  User alice\n"
        "  Port 22\n"
        f"  IdentityFile {resolved_identity}\n"
        "  LocalForward 5432 127.0.0.1:5432\n"
    )

    assert output == expected


def test_identity_file_relative_resolution(tmp_path: Path) -> None:
    config = Config(
        version=1,
        hosts=[
            Host(
                alias="db",
                host_name="db.example.com",
                identity_file="keys/id_rsa",
            )
        ],
    )
    config_path = tmp_path / "xzssh.json"

    output = render_openssh(config, config_path)
    expected_path = (tmp_path / "keys" / "id_rsa").resolve(strict=False)
    assert f"IdentityFile {expected_path}" in output
