"""Tests for the safety guarantees we promise:

- ``xzssh generate`` refuses to clobber a user-authored ssh_config.
- ``xzssh generate`` always saves a ``.bak`` when overwriting.
- ``write_config`` persists atomically (no truncated file on crash).
- The JSON source file is restricted to owner read/write on POSIX.
"""
from __future__ import annotations

import os
import stat
import sys
from pathlib import Path

import pytest

from xzssh.cli.helpers import write_config
from xzssh.cli.main import main
from xzssh.model import Config, Host


posix_only = pytest.mark.skipif(
    os.name != "posix", reason="POSIX permission semantics"
)


def _seed_xzssh_config(config_path: Path) -> None:
    main(
        [
            "add",
            "--config",
            str(config_path),
            "--alias",
            "db",
            "--host-name",
            "db.example.com",
        ]
    )


def test_generate_refuses_to_overwrite_user_authored_file(tmp_path: Path) -> None:
    config_path = tmp_path / "xzssh.json"
    output_path = tmp_path / "ssh_config"
    _seed_xzssh_config(config_path)

    user_content = "# my hand-rolled ssh config\nHost myhost\n  HostName 1.2.3.4\n"
    output_path.write_text(user_content, encoding="utf-8")

    exit_code = main(
        [
            "generate",
            "--config",
            str(config_path),
            "--output",
            str(output_path),
        ]
    )

    assert exit_code == 1
    assert output_path.read_text(encoding="utf-8") == user_content
    assert not output_path.with_name(output_path.name + ".bak").exists()


def test_generate_force_overwrites_user_file_and_saves_backup(tmp_path: Path) -> None:
    config_path = tmp_path / "xzssh.json"
    output_path = tmp_path / "ssh_config"
    _seed_xzssh_config(config_path)

    user_content = "# my hand-rolled ssh config\nHost myhost\n  HostName 1.2.3.4\n"
    output_path.write_text(user_content, encoding="utf-8")

    exit_code = main(
        [
            "generate",
            "--config",
            str(config_path),
            "--output",
            str(output_path),
            "--force",
        ]
    )

    assert exit_code == 0
    assert "Generated by xzSSH" in output_path.read_text(encoding="utf-8")

    backup_path = output_path.with_name(output_path.name + ".bak")
    assert backup_path.exists()
    assert backup_path.read_text(encoding="utf-8") == user_content


def test_generate_overwrites_own_output_without_force(tmp_path: Path) -> None:
    config_path = tmp_path / "xzssh.json"
    output_path = tmp_path / "ssh_config"
    _seed_xzssh_config(config_path)

    # First generation creates a header-bearing file.
    assert (
        main(
            [
                "generate",
                "--config",
                str(config_path),
                "--output",
                str(output_path),
            ]
        )
        == 0
    )
    first = output_path.read_text(encoding="utf-8")

    # Add another host then regenerate without --force; should succeed
    # because the existing file IS xzSSH-generated.
    main(
        [
            "add",
            "--config",
            str(config_path),
            "--alias",
            "web",
            "--host-name",
            "web.example.com",
        ]
    )
    assert (
        main(
            [
                "generate",
                "--config",
                str(config_path),
                "--output",
                str(output_path),
            ]
        )
        == 0
    )

    rewritten = output_path.read_text(encoding="utf-8")
    assert "Host db" in rewritten
    assert "Host web" in rewritten
    assert rewritten != first


def test_generate_treats_empty_output_as_safe_to_overwrite(tmp_path: Path) -> None:
    config_path = tmp_path / "xzssh.json"
    output_path = tmp_path / "ssh_config"
    _seed_xzssh_config(config_path)

    output_path.write_text("", encoding="utf-8")

    exit_code = main(
        [
            "generate",
            "--config",
            str(config_path),
            "--output",
            str(output_path),
        ]
    )
    assert exit_code == 0
    assert "Generated by xzSSH" in output_path.read_text(encoding="utf-8")


def test_generate_no_backup_when_target_does_not_exist(tmp_path: Path) -> None:
    config_path = tmp_path / "xzssh.json"
    output_path = tmp_path / "ssh_config"
    _seed_xzssh_config(config_path)

    main(
        [
            "generate",
            "--config",
            str(config_path),
            "--output",
            str(output_path),
        ]
    )

    assert not output_path.with_name(output_path.name + ".bak").exists()


@posix_only
def test_write_config_chmod_600(tmp_path: Path) -> None:
    config_path = tmp_path / "xzssh.json"
    cfg = Config(version=1, hosts=[Host(alias="db", host_name="db.example.com")])

    write_config(config_path, cfg)

    mode = stat.S_IMODE(config_path.stat().st_mode)
    assert mode == 0o600, f"expected 0o600, got {oct(mode)}"


@posix_only
def test_generate_chmod_600_on_output(tmp_path: Path) -> None:
    config_path = tmp_path / "xzssh.json"
    output_path = tmp_path / "ssh_config"
    _seed_xzssh_config(config_path)

    main(
        [
            "generate",
            "--config",
            str(config_path),
            "--output",
            str(output_path),
        ]
    )

    mode = stat.S_IMODE(output_path.stat().st_mode)
    assert mode == 0o600, f"expected 0o600, got {oct(mode)}"


def test_write_config_leaves_no_tmp_file_behind(tmp_path: Path) -> None:
    config_path = tmp_path / "xzssh.json"
    cfg = Config(version=1, hosts=[Host(alias="db", host_name="db.example.com")])

    write_config(config_path, cfg)

    siblings = list(tmp_path.iterdir())
    assert config_path in siblings
    assert all(not s.name.endswith(".tmp") for s in siblings), siblings
