from __future__ import annotations

from pathlib import Path
from typing import List

from xzssh.model import Config
from xzssh.platform import resolve_path


HEADER_LINE = "# Generated by xzSSH - DO NOT EDIT"


def render_openssh(config: Config, source_path: Path) -> str:
    lines: List[str] = [HEADER_LINE]

    for host in config.hosts:
        lines.append(f"Host {host.alias}")
        lines.append(f"  HostName {host.host_name}")
        if host.user is not None:
            lines.append(f"  User {host.user}")
        if host.port is not None:
            lines.append(f"  Port {host.port}")
        if host.identity_file is not None:
            resolved = resolve_identity_file(host.identity_file, source_path)
            lines.append(f"  IdentityFile {resolved}")
        if host.proxy_jump is not None:
            lines.append(f"  ProxyJump {host.proxy_jump}")
        for local_forward in host.local_forwards:
            lines.append(
                "  LocalForward "
                f"{local_forward.local_port} "
                f"{local_forward.remote_host}:{local_forward.remote_port}"
            )

    return "\n".join(lines) + "\n"


def resolve_identity_file(identity_file: str, source_path: Path) -> str:
    path = resolve_path(identity_file, source_path.parent)
    return str(path)
